Starting libraries and Learning Python adv.

In [35]:
import numpy as np

In [36]:
arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [37]:
print("separations")
b=[1,2,3,4,5]
print(b)

separations
[1, 2, 3, 4, 5]


In [38]:

#2D array - the array of arrays 

print("separations")
arr2 = np.array([[1,3,4,4,4],[6,7,8,45,4]])
print(arr2)

separations
[[ 1  3  4  4  4]
 [ 6  7  8 45  4]]


In [39]:
#3D array-
print("separations")
arr3 = np.array([[[1,2,3],[4,5,6]],[[3,2,1],[7,8,9]]])
print(arr3)

separations
[[[1 2 3]
  [4 5 6]]

 [[3 2 1]
  [7 8 9]]]


In [40]:
# check datatypes of array-

print(arr1.dtype)


int32


In [41]:
# check dimension of array-
print(arr2.ndim)
print(arr3.ndim)


2
3


In [42]:
# chect array shape-

print(arr3.shape)

(2, 2, 3)


In [43]:
# check size of array-
print(arr3.size)

12


In [44]:
#check item size of array-
print(arr3.itemsize)

4


In [45]:
# create array with zeroes-
arr_zeros =  np.zeros((2,3))
print(arr_zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [46]:
arr4_zeros =  np.zeros((2, 2,3))
print(arr4_zeros)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [47]:
#create array with ones-
arr4_ones =  np.ones((2, 2,3))
print(arr4_ones)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [48]:
#create array with random values
# rand() -values b/w 0 and 1
arr_random = np.random.rand(2,3)
# print(arr_random)

In [49]:
arr_random = np.random.rand(10)
# print(arr_random)

In [50]:
# -value b/w -ve to +ve 
arr_random = np.random.randn(10)
# print(arr_random)

In [51]:
#randit()- integer values b/w given range
np.random.randint(1,100 , size=(3,4))


array([[35, 95, 88, 88],
       [ 2, 21, 53, 33],
       [ 4,  9, 95, 54]])

In [55]:
#create array with specific range-
# arr_range = np.range((1, 20, 5))
# print(arr_range)

In [67]:
#array reshaping-
arr_int = np.array([1,2,3,3,4,5,6,4,6,7,8,4])
arr_reshad = arr_int.reshape(3,4)

In [69]:
# array indexing
print(arr_reshad[1,2])

6


In [70]:
#array slicing-
print(arr_reshad[0:2, 1:3])

[[2 3]
 [5 6]]


In [72]:
# array iteration
for i in arr_int:
# for i in arr_reshad:
    print(i)

1
2
3
3
4
5
6
4
6
7
8
4


In [ ]:
# array math operations-

arrx = np.array([1,2,3,4,5])
arry = np.array([5,6,7,9,8])


In [75]:
add = arrx + arry
print(add)

[ 6  8 10 13 13]


In [76]:
arrz = np.array([[1,2,3,4,5],[1,2,3,4,5]])
arrv = np.array([[1,4,5,6,7],[9,8,7,6,4]])

print(arrz + arrv)


[[ 2  6  8 10 12]
 [10 10 10 10  9]]


Stratistical Operations-

In [ ]:
print(np.mean(arrx))
print(arrx.sum())
print(np.median(arry)) 
print(np.var(arry)) 
print(np.min(arry)) 
print(np.max(arry)) 
print(np.percentile(arry,40)) 
print(np.sort(arry)) 

3.0
15
7.0
2.0
5
9
6.6
[5 6 7 8 9]


In [ ]:
print(np.unique(arrx))
print(np.sqrt(arrx))

[1 2 3 4 5]
[1.         1.41421356 1.73205081 2.         2.23606798]


Search and Filter any values-

In [80]:
print(np.where(arr1>3))
print(arr2[arr2>4])

(array([3, 4], dtype=int64),)
[ 6  7  8 45]


Copy and View-
Copy does not change the original data, but View does.

In [83]:
arr_copy = arr1.copy()
arr_view = arr1.view()

arr_copy[0]= 40
print(arr1)
print(arr_copy)


[1 2 3 4 5]
[40  2  3  4  5]


In [86]:
arr_view[2]= 500
print(arr1)
print(arr_view)

[  1   2 500   4   5]
[  1   2 500   4   5]
